name: Destroy AWS Resources

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: "Environment name (e.g. slot-gui-master)"
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          ENV_NAME: ${{ github.event.inputs.env_name }}
        run: |
          cd terraform
          terraform init -backend-config="key=envs/${ENV_NAME}/terraform.tfstate"
          terraform destroy -auto-approve -var="env_name=$ENV_NAME"
