name: Upload app.zip to S3

on:
  push:
    branches: [master]   # or your chosen branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: slot-gui

      - name: Build static site
        run: npm run build
        working-directory: slot-gui

      - name: Zip app for deployment
        run: cd slot-gui && zip -r ../app.zip . -x ".git/*" "node_modules/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload app.zip to S3
        run: aws s3 cp app.zip s3://slot-gui-deploy-micqdf-20240601/app.zip

