name: Upload app.zip to S3

on:
  push:
    branches: [master]   # or your chosen branch

jobs:
  upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: slot-gui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip app for deployment
        run: zip -r ./app.zip ./slot-gui

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload app.zip to S3
        run: aws s3 cp ./app.zip s3://slot-gui-deploy-micqdf-20240601/app.zip

