name: Deploy to S3 for Beanstalk

on:
  push:
    branches: [master]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker build (test container)
        run: |
          cd slot-gui
          docker build -t slot-gui-bun .

      - name: Zip all build artifacts for Beanstalk
        run: |
          cd slot-gui
          zip -r ../app.zip . 
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 cp app.zip s3://slot-gui-deploy-micqdf-20240601/app.zip

